services:
  conexus-hub-front:
    image: ${DOCKER_USERNAME}/conexus-hub-front:${TAG}
    ports:
      - "80:5173"
    environment:
      - NODE_ENV=production
      - VITE_API_URL=${VITE_API_URL}
    restart: unless-stopped
    networks:
      - conexus-hub-network

  conexus-hub-back:
    image: ${DOCKER_USERNAME}/conexus-hub-back:${TAG}
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - JWT_SECRET=${JWT_SECRET}
    restart: unless-stopped
    depends_on:
      - conexus-hub-mysql
    networks:
      - conexus-hub-network

  conexus-hub-mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
    restart: unless-stopped
    networks:
      - conexus-hub-network

volumes:
  mysql-data:


networks:
  conexus-hub-network:
    driver: bridge
